### ISSUE TITLE
[疑问]如果使用完整的jdk发行版是不是不用加如某些依赖?

### ISSUE THREAD

**Issue by LordHumphrey** [icuxika/JavaFX-Package-Sample#1]
[bellsoft-jdk](https://bell-sw.com/)带完整的javafx,但是和gradle那些依赖配置有些冲突,不知道咋弄呢,大佬有空可以研究下吗?谢谢

**Comment by icuxika** [comment]
> [bellsoft-jdk](https://bell-sw.com/)带完整的javafx,但是和gradle那些依赖配置有些冲突,不知道咋弄呢,大佬有空可以研究下吗?谢谢

我试了下，注释掉相关依赖，没什么冲突啊，下载的这个版本 **Liberica Full JDK 16.0.1+9 x86 64 bit for Windows**。
build.gradle 依赖处更新为
`
dependencies {
    implementation("com.squareup.okhttp3:okhttp:4.9.0")
    implementation("com.jfoenix:jfoenix:9.0.10")
    testImplementation("junit:junit:4.12")
}
`

module-info.java 更新为
`
module sample {
    requires com.jfoenix;
    requires javafx.graphics;
    exports com.icuxika;
}
`
然后运行的时候请确保gradle也是使用的是 **Liberica Full JDK 16.0.1+9 x86 64 bit for Windows**

**Comment by icuxika** [comment]
@LordHumphrey 你应该解决了吧，此issue就关闭了
