### ISSUE TITLE
菜鸡的我有个疑问

### ISSUE THREAD

**Issue by shanghua521** [icuxika/JavaFX-Package-Sample#2]
我可以在 Ubuntu 平台打包一个 exe 吗。换言之，可以在 windows 打包一个 Linux 下 的文件吗

**Comment by icuxika** [comment]
@shanghua521 不好意思现在才看到，即使是OpenJdk和JavaFX的源码编译官方也只提供了的各个平台的文档，没看到在一个平台的编译其他平台的内容，另外，我之前自己编译过JavaFX的源码，他的有些模块比如media，是和Windows深度耦合的，这些问题感觉很难使JavaFX程序跨平台编译，当然我的知识比较有限，也只了解到像C、C++程序有跨平台编译，但自己并未实际操作过。

**Comment by shanghua521** [comment]
明白了，谢谢解答
