### ISSUE TITLE
没整明白，求指导，谢谢。

### ISSUE THREAD

**Issue by tenglongwentian** [icuxika/JavaFX-Package-Sample#4]
环境：idea2021.3.1，Windows10 pro 64bit，openjdk17.0.1，maven3.8.3，javafx版本17.0.1

**Comment by icuxika** [comment]
@tenglongwentian 有遇到的报错信息的截图吗？项目jdk版本设置为17，对于maven来说两种思路：一、自jdk11提供的jlink命令和jdk14提供的jpackage命令手动来完成，先执行命令 `mvn package`，此步骤会构建没有清单的项目的jar包，并将项目所依赖的第三方依赖复制到一个指定目录下，然后如果想要构建可执行程序则执行 `mvn exec:exec@image`，这个步骤相当于创建一个绿色解压缩版本的软件目录，也可以执行 `mvn exec:exec@installer`这是根据不同系统平台构建出符合系统要求的安装程序，如果是Windows，你需要安装wix toolset工具集，并将它的bin目录添加到环境变量中；二、基于JavaFX官方提供的maven插件，执行`mvn javafx:jlink`也会构建出类似第一步中`mvn exec:exec@image`的效果，但在win上，将只会有一个bat脚本用来启动程序，而没有exe产生，这是因为jlink和jpackage的区别，但是产生bat脚本后，依然可以通过jpackage命令构建出exe或者安装程序，ReadMe文件中描述的挺清楚的。

### 视频教程（jdk15时录制，但步骤几乎一样，视频中一些特殊问题在java17已经得到解决）
https://www.bilibili.com/video/BV1BK4y1W72q/

### 补充说明
- 在Windows下，请将本项目关于程序图标的配置路径改为/src/main/resources/application.ico
- mvn exec:exec@根据不同值可以执行不同命令的配置没有在idea侧边栏中显示出来，由于我使用maven较少，所以不是很明确，建议对于此项目在cmd通过`set JAVA_HOME=""`，设置临时环境变量调用mvn命令，然后每次重新调用之前`mvn clean`一下

**Comment by tenglongwentian** [comment]
@icuxika 
环境：idea2021.3.1，Windows10 pro 64bit，openjdk17.0.1，maven3.8.3，javafx版本17.0.1，javafx-jmods-17.0.1，javafx-sdk-17.0.1，WiX Toolset v3.11，SceneBuilder-17.0.0，如果是msi的话，将--type的值由exe改为msi即可。
如下是配置信息：
`
<execution>
                        <id>win-exe</id>
                        <goals>
                            <goal>exec</goal>
                        </goals>
                        <configuration>
                            <executable>jpackage</executable>
                            <workingDirectory>${project.basedir}</workingDirectory>
                            <arguments>
                                <argument>--name</argument>
                                <argument>Calculator</argument>
                                <argument>--type</argument>
                                <argument>exe</argument>
                                <argument>--input</argument>
                                <argument>${project.build.directory}</argument>
                                <argument>--dest</argument>
                                <argument>${project.build.directory}</argument>
                                <argument>--main-jar</argument>
                                <argument>${project.build.directory}/${project.artifactId}-${project.version}.jar</argument>
                                <argument>--main-class</argument>
                                <argument>com.calculator.HelloApplication</argument>
                                <argument>--module-path</argument>
                                <argument>"C:\Program Files\Java\openjdk\javafx-jmods-17.0.1"</argument>
                                <argument>--add-modules</argument>
                                <argument>javafx.controls,javafx.fxml</argument>
                                <argument>--win-shortcut</argument>
                                <argument>--win-menu</argument>
                                <argument>--win-menu-group</argument>
                                <argument>Calculator</argument>
                                <argument>--icon</argument>
                                <argument>${project.basedir}/src/main/resources/icon.ico</argument>
                                <argument>--app-version</argument>
                                <argument>1.0.0</argument>
                                <argument>--win-dir-chooser</argument>
                                <argument>--win-shortcut-prompt</argument>
                            </arguments>
                        </configuration>
                    </execution>
`
![image](https://user-images.githubusercontent.com/18063792/149625146-b51f7339-5b46-4504-a86e-027afb5efebb.png)
还有一个问题，在Windows开发环境下，能否打包为rpm（Linux）或dmg（Mac OSX）。
本地经过尝试，如下配置，执行报错：错误：选项 [--linux-package-name] 在此平台上无效。
`
<argument>--type</argument>
                                <argument>rpm</argument>
<argument>--linux-package-name</argument>
                                <argument>Calculator</argument>
                                <argument>--linux-app-release</argument>
                                <argument>1.0.0</argument>
                                <argument>--linux-shortcut</argument>
                                <argument>--linux-menu-group</argument>
                                <argument>Calculator</argument>
`

**Comment by icuxika** [comment]
@tenglongwentian 跨平台构建安装包这个目标本身就比较困难，像Windows上你需要手动安装wix toolset，而在Linux比如Deepin上你也需要通过apt安装一些东西额外的东西才能构建出installer，但是这个exe及msi这种安装包主要还是jpackage命令所提供的功能；而对于jlink，即你通过maven的JavaFX插件执行`mvn javafx:jlink` 或单独使用jlink命令可以产生bat（win）脚本的同时会产生linux的shell脚本，制作成压缩包放到其他平台我觉得是可以运行的，但这种我没尝试过，毕竟一个Deepin虚拟机就能完成测试。jpackage及相关的配置跨平台目前看似不可行，毕竟JavaFX本身编译的说明文档都是各个平台有着不同的配置。

**Comment by icuxika** [comment]
@tenglongwentian  你使用了maven后，就不需要下载jmods文件了，maven引入的JavaFX相关依赖放在module-path就可以了，这样这个命令不需要额外配置jmods路径就可以在不同系统平台直接运行了，当前项目只需要更换一下图标路径，亦可以参考下　[FXIconCreator](https://github.com/lanthale/FXIconCreator)　配置。

**Comment by icuxika** [comment]
关啦
