### ISSUE TITLE
[周二 4月 12 21:37:19 CST 2022][严重] Downloading failed: https://download2.gluonhq.com/substrate/javafxstaticsdk/openjfx-18-ea+2-windows-x86_64-static.zip

### ISSUE THREAD

**Issue by 19chang19** [icuxika/JavaFX-Package-Sample#5]
[周二 4月 12 21:37:19 CST 2022][严重] Downloading failed: https://download2.gluonhq.com/substrate/javafxstaticsdk/openjfx-18-ea+2-windows-x86_64-static.zip

**Comment by icuxika** [comment]
Jdk18等到这个项目依赖的插件满足了，我会更新一下，目前没啥时间，通过graalvm对JavaFX程序进行aot构建，依赖它提供的一些东西，你这个报错可能是因为这个下载被墙了，网络不好，还没有到实际构建的阶段。
