### ISSUE TITLE
JDK 17 示例运行遇两问题

### ISSUE THREAD

**Issue by KunMinX** [icuxika/JavaFX-Package-Sample#6]
1.start 方法 JFXTabPane 等控件均导致项目无法运行

2.生成 jar 通过 java -jar 命令运行提示 `jar中没有主清单属性`

**Comment by KunMinX** [comment]
问题 2 已解决，在 gradle 中添加 jar 闭包即可

**Comment by KunMinX** [comment]
目前在用 JDK17，JavaFx SDK 也需额外下载，不然跑 jar 时提示 “找不到主类，原因是找不到 javafx.application”

**Comment by icuxika** [comment]
> 目前在用 JDK17，JavaFx SDK 也需额外下载，不然跑 jar 时提示 “找不到主类，原因是找不到 javafx.application”

这个问题应该是直接在idea中运行main方法带来的，有两种解决办法，第一种：通过gradle run命令，这毕竟是个gradle项目，与直接通过main方法运行，对于JavaFX有些不同，第二种：新建一个启动类，比如Launcher.java，然后在里面新建一个main方法来调MainApp的main方法来运行，就可以直接通过idea主方法来执行了

**Comment by icuxika** [comment]
> 1.start 方法 JFXTabPane 等控件均导致项目无法运行
> 
> 2.生成 jar 通过 java -jar 命令运行提示 `jar中没有主清单属性`

对于第一个问题，你目前拉取的是java17（18换了一个新的库）的分支对吧，这个旧的库与Java9开始的模块化不是很兼容，所以可以在build.gradle或者pom.xml中看到类似
```
--add-exports=javafx.controls/com.sun.javafx.scene.control.behavior=com.jfoenix
```
这样的配置，而直接通过idea主方法可能会无法生效这些配置，默认不会携带这个jvm参数，
补充一下 maven方面，运行的话，建议通过`mvn javafx:run`来运行

**Comment by KunMinX** [comment]
感谢解答，示例项目现可打包运行了
