### ISSUE TITLE
B站用户前来报到

### ISSUE THREAD

**Issue by 512002613** [icuxika/JavaFX-Package-Sample#7]
项目梗概： 该项目设计为对OFFICE进行操作的Gui工具
引入Poi 5.3.2版本
JAVA环境为JAVA17
开发调试功能正常
采用VMOPTION配置JAVAFX_JDK 解决JAVAFX的组件化问题
在采用Jlink进行打包的时候出现了以下问题并打包失败

[INFO] --- maven-compiler-plugin:3.8.1:compile (default-compile) @ demo ---
[WARNING] *********************************************************************************************************************************************************************************************
[WARNING] * Required filename-based automodules detected: [commons-math3-3.6.1.jar, SparseBitSet-1.2.jar, validatorfx-0.1.13.jar]. Please don't publish this project to a public artifact repository! *
[WARNING] *********************************************************************************************************************************************************************************************
[INFO] Nothing to compile - all classes are up to date

**Comment by icuxika** [comment]
不好意思，这一周有些事情，一直没时间用电脑。今天做了些测试，对于`org.apache.poi:poi:5.2.3`这个依赖，在maven下，确实难以使用jlink，当前使用的[Maven plugin for JavaFX](https://github.com/openjfx/javafx-maven-plugin)很久没有更新，对于自动模块的支持也不足，不过在使用gradle构建项目时，使用的[Badass JLink Plugin](https://github.com/beryx/badass-jlink-plugin)对此有支持能够正常进行构建，如果你的项目较为简单的话，不妨尝试一下gradle，只不过gradle需要vpn才能更好的使用，另一方面同一作者提供的用于非模块化项目（即项目中没有提供`module-info.java`但又要使用jpackage构建出应用）[Badass Runtime Plugin](https://github.com/beryx/badass-runtime-plugin)的插件可以用起来更方便些，maven相关的我再去外网翻翻，关于模块化的东西可以看看[【JDK 11】关于 Java 模块系统，看这一篇就够了](http://emacoo.cn/coding/java-module-system/)，可以了解下插件大概需要怎么做能融合非模块化的jar包到模块化项目中。

如果你要在这个项目中尝试下gradle得话，可以修改项目中两个文件对应内容为：
1、`build.gradle`
```
dependencies {
//    implementation "org.openjfx:javafx-base:${javaFXVersion}:${platform}"
//    implementation "org.openjfx:javafx-controls:${javaFXVersion}:${platform}"
//    implementation "org.openjfx:javafx-graphics:${javaFXVersion}:${platform}"
//    implementation "org.openjfx:javafx-fxml:${javaFXVersion}:${platform}"
//    implementation "org.openjfx:javafx-swing:${javaFXVersion}:${platform}"
//    implementation "org.openjfx:javafx-media:${javaFXVersion}:${platform}"
//    implementation "org.openjfx:javafx-web:${javaFXVersion}:${platform}"

    implementation("io.github.palexdev:materialfx:11.13.5")
    implementation("org.apache.poi:poi:5.2.3")
}
```
2、`MainApp`
```
        enButton.setOnAction(new EventHandler<ActionEvent>() {
            @Override
            public void handle(ActionEvent actionEvent) {
                try (HSSFWorkbook workbook = new HSSFWorkbook()) {
                    HSSFSheet sheet = workbook.createSheet("test");
                    HSSFRow row = sheet.createRow(0);
                    HSSFCell cell = row.createCell(0);
                    cell.setCellValue(true);
                    workbook.write(new FileOutputStream("/Users/icuxika/temp/test.xls"));
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });
```

**Comment by 512002613** [comment]
好的谢谢回答。对我挺有启发的。我这边采用的解决思路是通过可执行jar包用jpackage命令进行封包



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年4月9日(周日) 晚上8:30
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [JavaFX-Starter/JavaFX-Package-Sample] B站用户前来报到 (Issue #7)




 
不好意思，这一周有些事情，一直没时间用电脑。今天做了些测试，对于org.apache.poi:poi:5.2.3这个依赖，在maven下，确实难以使用jlink，当前使用的Maven plugin for JavaFX很久没有更新，对于自动模块的支持也不足，不过在使用gradle构建项目时，使用的Badass JLink Plugin对此有支持能够正常进行构建，如果你的项目较为简单的话，不妨尝试一下gradle，只不过gradle需要vpn才能更好的使用，另一方面同一作者提供的用于非模块化项目（即项目中没有提供module-info.java但又要使用jpackage构建出应用）Badass Runtime Plugin的插件可以用起来更方便些，maven相关的我再去外网翻翻，关于模块化的东西可以看看【JDK 11】关于 Java 模块系统，看这一篇就够了，可以了解下插件大概需要怎么做能融合非模块化的jar包到模块化项目中
